# Site settings
title: thereadme
email: hi@theread.me
description: a rabbit hole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://theread.me" # the base hostname & protocol for your site

date_format: "%b %d, %Y"

# Build settings
markdown: kramdown
permalink: /:title/
redcarpet:
  extensions: ["strikethrough"]

collections:
  art:
    title: art
    permalink: /art/:path/

contentsLabel: "Table of Contents"
showToggleButton: true

scholar:
  style: apa

